### ISSUE TITLE
"Introduction" is missing in mobile menu

### ISSUE THREAD

**Issue by davehakkens** [leo/plastic#34]
The introduction link is missing at the start section in the mobile menu 
![image](https://cloud.githubusercontent.com/assets/13672737/13936571/e26b7f7e-efbe-11e5-83d7-e1a413f85aa4.png)

**Comment by leo** [comment]
I've made it hidden for the smaller screen version because it broke out of the container:

<img width="819" alt="screen shot 2016-03-22 at 12 07 24" src="https://cloud.githubusercontent.com/assets/6170607/13949676/c54dd15e-f026-11e5-9533-f40f4b608cf4.png">

Besides of that, the "Intro" link does the same action as the "Start" button in the big menu, doesn't it? So looking at accessibility, it's not needed, if you ask me. :blush:

**Comment by davehakkens** [comment]
well it is a bit weird. But I can live with that! Can we get it back on mobile?
