### ISSUE TITLE
Remove frameborders

### ISSUE THREAD

**Issue by theel0ja** [leo/plastic#76]
Remove those ugly frameborders.
![image](https://cloud.githubusercontent.com/assets/5832930/19832313/84a85f8c-9e29-11e6-92bf-55126e613bc9.png)
Page: [preciousplastic.com/en/videos/map](https://preciousplastic.com/en/videos/map/)

**Comment by davehakkens** [comment]
Do it!

On 29 October 2016 at 21:47:24, Elias Ojala (notifications@github.com)
wrote:

Remove those ugly frameborders.
[image: image]
https://cloud.githubusercontent.com/assets/5832930/19832313/84a85f8c-9e29-11e6-92bf-55126e613bc9.png
Page: preciousplastic.com/en/videos/map

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/hakkens/precious-plastic/issues/76, or mute the thread
