### ISSUE TITLE
News isn't loading

### ISSUE THREAD

**Issue by thisismattia** [leo/plastic#80]
https://preciousplastic.com/en/news/

![image](https://user-images.githubusercontent.com/17761877/27859501-3be7493e-6179-11e7-9b8e-3fc32320301d.png)

**Comment by davehakkens** [comment]
Do we keep news?


On 5 July 2017 at 11:58:27, Mattia (notifications@github.com) wrote:

https://preciousplastic.com/en/news/

[image: image]
<https://user-images.githubusercontent.com/17761877/27859501-3be7493e-6179-11e7-9b8e-3fc32320301d.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/hakkens/precious-plastic/issues/80>, or mute the thread
